<div class="container-fluid">
	<div class="row">
		<div class="col-12 col-md-10 col-xl-8 mx-auto">
			<div class="customer-testimonial">
				<img src="../images/testimonials/testimonial-16-lg.jpg" class="img-fluid d-flex mx-auto">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-md-10 col-xl-8 mx-auto">
			<div class="customer-testimonial mb-5 mt-4">
				<h4>I have learned what is genuine Fengshui.</h4>
				<h6 class="mb-4">Client：Ellson Tan</h6>
				<p>Before sharing my thoughts, I would like to wish Master Loh’s Fengshui Republic a happy 10th anniversary, and his success in leading Fengshui Republic to expand for international market, and international acknowledgement. This is not something easy, but Master Loh managed to do it, and his secrets are his professionalism, making him a trustworthy Fengshui Metaphysician and a Fengshui Master of renowned reputation. Since I was 18 years old, I started to be curious in the mysterious Fengshui and Chinese Metaphysics, but they appear to be half-true and half-fake, and I was doubtful if they are really logical. So I was half-skeptic and a half-believer in my journey to search for answer, and I frequently went to bookstores to look for books on Fengshui and Metaphysics to find the answers. Day after day, month after month and year after year, I still kept researching on Fengshui and Metaphysics yet I could not find my answers. As Facebook becomes more popular and even a necessary, I saw information shared by my friends and I found Master Loh’s fan page, where he shares a lot of information on Fengshui. I read all the articles shared by Master Loh carefully, and they answered a lot of my question. Fengshui is indeed knowledge we inherited from the ancient people, and it has solid base. Last year, I went to Kuala Lumpur to attend the house-warming party of a relative, and we talked about Master Loh’s Fengshui classes which would begin this year. I was indecisive if I should enroll myself in the classes, the relative then gave me an entrance ticket to Master Loh’s Fengshui Convention, and mentioning that she got the free ticket from Korea Wallpaper when he bought some wallpapers. That moment I started to feel I have affinity with Master Loh, and the Fengshui Convention ticket was given to me as I was having the thought of meeting him. I was very happy and thought that perhaps God intended me to meet Master Loh. After coming back home I started to browse through Master Loh’s webpage and found out the price list for the courses, and the charges were indeed reasonable, even cheaper than what I previously thought. On the day of the convention, because I was not familiar with Kuala Lumpur and was afraid that I would be late, I started driving from my hometown as early as 4 in the morning to KLCC Plenary Hall. When I reached the venue, the convention had yet to start, so I took the time to ask the staffs about the courses offered and made my registration. Actually, I had never met Master Loh; I only knew about his professional analysis through Facebook and TV programs, and it is his trustworthiness and the genuine Fengshui knowledge he presented that convinced me to join the courses. During the convention, Master Loh shared a lot of Fengshui and Chinese Metaphysical knowledge, and his humorous, fun style of presentation captivated everyone; I would want to attend Master Loh’s convention every year.</p>
				<p>Finally, Master Loh’s Beginner Fengshui class would start in March this year. I was nervous on that day, as I thought Fengshui Masters would be arrogant and they might even scold me if I ask questions. So I stepped inside Fengshui Republic to wait for Master Loh to come, and the impression I had was the place was comfortable and its decorations, arrangements and lighting were different from others; Master Loh definitely placed a lot of efforts in this. That day, Master Loh patiently taught us the basic knowledge in Fengshui like the greater environment and natural surroundings. There are of course more things taught by Master Loh; if you wish to know more, just contact Fengshui Republic. After experiencing Master Loh’s teaching methods, which make difficult subjects easy, I have learned what is genuine Fengshui. After attending his courses, you will find out many commonly circulated Fengshui knowledges are in fact incorrect; they are either superstitious or misleading. Fengshui is important to everyone, because Fengshui can bring us health, harmony, safety, wealth and others. Some thought you do not need to work hard if there is Fengshui, but Fengshui is not magic and will not bring money to you out of nowhere. Good Fengshui can generate good fortune, wellness, harmony in family, help from good people and improve your career to gather wealth; your wealth will not be dropped from heaven. Other than Fengshui, many people have ignored Bazi and Chinese metaphysics. Sometimes when we have experienced negativities in our career or in our family, it is likely that has to do with our Bazi, and has nothing to do with Fengshui. What exactly is Bazi? When it comes to Bazi, many people would think about fortune-telling, but again what is fortune-telling? Is it wealth prediction? Or is it lottery number prediction? Actually, the real Bazi is about understanding your own personalities, strengths, weaknesses, which career path suits you the most, whether you are suitable to be an entrepreneur or a salaried worker, the right time to start your own business, the best opportunities for your development and others. Bazi is like a car, and your fortune is like the road; a good car and a good road can bring you to your destination faster, but those who drive a normal car should not be upset because you still can choose a better road to reach your destination albeit you might need to spend a little bit more time to achieve success, but of course this is better than driving to the wrong roads and unable to reach your destination. Now you see how important Bazi is, and it is through understanding our destiny that we will not make wrong decisions to delay our success.</p>
				<p>It is said that our life is determined by these, in sequence:</p>
				<ol>
					<li>Fate</li>
					<li>Luck</li>
					<li>Fengshui</li>
					<li>Merits</li>
					<li>Education</li>
					<li>Name</li>
					<li>Facial feature</li>
					<li>Faith</li>
					<li>Helpful people</li>
					<li>Taking care of our own well-being</li>
					<li>Career choice and spouse</li>
					<li>Knowing how to avoid disasters</li>
				</ol>
				<p>Now we see that name is at the 6th of the rank. Name is important for everyone; there is no one that has no name. When a child is born, the parents would want the best name for the child, because the name is the code of one’s life and will be used until the end of one’s life time and will be remembered by others. A good name can boost one’s luck and attract helpful people. If you have a good name, you don’t even need to seek for these helpful people, they will come to you instead. Many of those who were born in the 1930s and 1940s would use animal names to call themselves, like Cow, Fire and Cat Poop; just think about it, can those people with these names enjoy good fortune?On the contrary, let us look at the name of Master Loh, the founder of Fengshui Republic. His Chinese name indicates that his name will spread far and wide; and since Fengshui Republic has free online name analysis service, I gave it a try. You too, can log on to the site and check your name. I keyed-in my Chinese name and the mark I got is 84, and that’s not bad. Name Selection does not just count in the Five Elements and strokes; the name should sound nice too. My Chinese name though is not bad, it can also be pronounced to sound like “becoming deaf” and surely no one wants to be deaf! That is way if you want to give a name to your child, remember to make it sound nice too, and seek Master Loh’s naming service at Fengshui Republic, so that your child can grow up to have a good and reputable name. And Master Loh often says, “it would be better to give a child a good name than a thousand gold”.I have learned a lot of valuable knowledge at Fengshui Republic, and all the instructors here answer all my questions. Fengshui Republic not just provides good and complete services, its instructors are knowledgeable and the team is not bad too. All of its clients have only praises for Fengshui Republic, and it is everyone’s first choice when they want to select a Fengshui company. Once again, I wish Master Loh a happy 10the year anniversary of Fengshui Republic.</p>
			</div>
		</div>
	</div>
</div>